name: pelada_chori
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo_pelada.png
    # - assets/   # (opcional) libera todo o diretório

# Configuração do gerador de ícones
flutter_launcher_icons:
  image_path: assets/logo_pelada.png
  web:
    generate: true
    image_path: assets/logo_pelada.png
    background_color: "#ffffff"
    theme_color: "#ff6a00"
  android: false
  ios: false
  windows:
    generate: false
  macos:
    generate: false
  linux:
    generate: false
